# Typos aliases.
alias sl='ls'

# Term colors.
# See http://ascii-table.com/ansi-escape-sequences.php
COLOR_DOMAIN="\[\033[0;37m\]" # white
COLOR_PATH="\[\033[1;34m\]"   # bold blue
COLOR_BRANCH="\[\033[1;33m\]" # yellow
COLOR_DOLLAR="\[\033[0;37m\]" # white
COLOR_NONE="\[\033[0m\]"      # reset
export PS1="$COLOR_DOMAIN\u@\h: $COLOR_PATH\w$COLOR_BRANCH \$(git rev-parse --abbrev-ref HEAD 2> /dev/null) $COLOR_DOLLAR\$$COLOR_NONE "

# Common directories.
export TOOLS=$HOME/Tools/
export SOURCES=$HOME/Projects/
export SCRIPTS=$TOOLS/Scripts/

export PATH=$TOOLS/depot_tools:$PATH:$SCRIPTS/git

source $SCRIPTS/blink.sh
source $SCRIPTS/chromium.sh

alias setup_Chromium="setup_Chromium_Env $SOURCES/Chromium/src"
alias setup_ChromiumGardening="setup_Chromium_Env $SOURCES/Gardening/ChromiumCommit/src"

alias setup_Blink="setup_Blink_Env $SOURCES/Blink/src"
alias setup_Blink_Glitter="setup_Blink_Env $SOURCES/GlitterBlink/src"

alias sc="setup_Chromium"
alias scg="setup_ChromiumGardening"

alias sb="setup_Blink"
alias sbg="setup_Blink_Glitter"

alias sp="cd ~/PrivateProjects/papyrus/google3/"

function checkout() {
    if [ $# -eq 0 ]
    then
        echo "Missing branch name"
        return 1
    fi

    git checkout $@
}
alias gco="git-co"
alias gcm="git checkout master"
alias grbc="git rebase --continue"
alias grba="git rebase --abort"

alias glb="git lb"
alias gd="git diff"
alias gdm="git diff master"

alias gca="git commit --amend"
alias gcaa="git commit --amend -a"

function git_grep_to_vim() {
    if [ -z $1 ]
    then
        echo "Usage: git_grep_to_vim pattern"
        return 1
    fi

    vim `git grep -l $1`
}
alias vig=git_grep_to_vim

alias gg="git grep"

# Ninja
export GYP_GENERATORS='ninja'

export CHROME_DEVEL_SANDBOX=/usr/local/sbin/chrome-devel-sandbox

# Private scripts.
export PATH=$PATH:$TOOLS/Private/git

# Override default perforce diff (gtkdiff).
export P4DIFF="diff -u"
